use std::path::PathBuf;

fn root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

#[test]
fn owner_source_imports_exact_producers_and_keeps_roles_empty() {
    let source = meta_signal_router::META_ROUTER_INTERFACE_SOURCE;
    assert!(source.starts_with("Interface.{1 0 0}\n[signal_router:lib.["));
    for imported in [
        "TimestampNanos",
        "EngineIdentifier",
        "ChannelIdentifier",
        "UnixUserIdentifier",
        "signal_standard:lib.[ComponentKind HostName NetworkEndpoint]",
    ] {
        assert!(source.contains(imported), "missing import: {imported}");
    }
    assert!(source.contains("MetaRouterRequest.["));
    assert!(source.contains("MetaRouterReply.["));
    assert!(source.contains("\n  []\n  []\n  []\n  ["));

    for copied in [
        "ChannelIdentifier.String",
        concat!("Component", "Name."),
        "EngineIdentifier.String",
        "HostName.String",
        concat!("Network", "Peer.String"),
        "TimestampNanoseconds.Integer",
        "UnixUserIdentifier.Integer",
    ] {
        assert!(
            !source.contains(copied),
            "copied declaration remains: {copied}"
        );
    }
}

#[test]
fn strict_projection_uses_encoded_local_and_imported_coordinates() {
    let generated = meta_signal_router::META_ROUTER_INTERFACE_RUST;
    assert!(generated.starts_with(
        "// @generated by schema-rust from an authority-verified bootstrap Interface\n\n"
    ));
    for visible in ["MetaRouterRequest", "MetaRouterReply", "ChannelGrant"] {
        assert!(!generated.contains(&format!("pub enum {visible}")));
        assert!(!generated.contains(&format!("pub struct {visible}")));
    }
    assert!(generated.contains("signal_router::schema::lib::z"));
    assert!(generated.contains("signal_standard::schema::lib::z"));
    assert_eq!(
        meta_signal_router::bootstrap_manifest::DECLARATION_SEATS.len(),
        70
    );
}

#[test]
fn strict_interface_is_the_sole_meta_router_schema_authority() {
    let root = root();
    assert!(!root.join("schema").exists());
    assert!(root.join("ethos/interface.ethos").is_file());
    assert_eq!(
        meta_signal_router::META_ROUTER_INTERFACE_SOURCE,
        include_str!("../ethos/interface.ethos")
    );
}
