// @generated by schema-rust from an authority-verified bootstrap Interface

pub enum z2VL5G {z2VeAc , z2VYfn , z2VT9k , z2VXST , z2VW1p ,} 
pub enum z2VXAD {z2VYnp , z2VLXv , z2VR31 ,} 
pub struct z2VSuA {
    pub field_0: z2VMzP,
    pub field_1: z2VXAD,
}
pub struct z2VShs(signal_router::schema::lib::z2VUhk);
impl z2VShs {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: signal_router::schema::lib::z2VUhk) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &signal_router::schema::lib::z2VUhk {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> signal_router::schema::lib::z2VUhk {
        self.0
    }
}
pub struct z2VSet(std::string::String);
impl z2VSet {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VYfp(std::string::String);
impl z2VYfp {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VRn4 {
    pub field_0: signal_router::schema::lib::z2VUhk,
    pub field_1: z2VXGr,
}
pub struct z2VXEz {
    pub field_0: z2Vbxp,
    pub field_1: z2Vbxp,
    pub field_2: Vec<z2VUWE>,
    pub field_3: z2VWgk,
}
pub struct z2VLSg {
    pub field_0: signal_router::schema::lib::z2VUhk,
    pub field_1: z2VWgk,
}
pub struct z2VPBk(signal_router::schema::lib::z2VUhk);
impl z2VPBk {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: signal_router::schema::lib::z2VUhk) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &signal_router::schema::lib::z2VUhk {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> signal_router::schema::lib::z2VUhk {
        self.0
    }
}
pub enum z2Vbxp {
    z2Va3A(z2VVrv),
    z2VWQw(signal_standard::schema::lib::z2VWWD),
}
pub struct z2VXGr(std::string::String);
impl z2VXGr {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VUEJ(signal_router::schema::lib::z2VUhk);
impl z2VUEJ {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: signal_router::schema::lib::z2VUhk) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &signal_router::schema::lib::z2VUhk {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> signal_router::schema::lib::z2VUhk {
        self.0
    }
}
pub enum z2VUWE {z2VLgY , z2VQ7g , z2VQpt , z2VUk4 , z2VQst , z2VMHW , z2VUNf , z2VKpa , z2VPd4 , z2Vciy , z2VL9V , z2VYrV ,} 
pub enum z2VWgk {
    z2VXGt(signal_router::schema::lib::z2VQGK),
    z2VbFb,
    z2VVUb,
}
pub struct z2VMyn ( z2VSet ,) ;
pub struct z2VbCv {
    pub field_0: z2VMzP,
    pub field_1: z2VL5G,
}
pub enum z2VMzP {z2VVom , z2VY6p , z2VenP , z2VYCD ,} 
pub struct z2VZs4(bool);
impl z2VZs4 {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: bool) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &bool {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> bool {
        self.0
    }
}
pub enum z2VVrv {
    z2VRvM(signal_standard::schema::lib::z2VaVE),
    z2VZTe(z2VYfp),
    z2VSk9(signal_router::schema::lib::z2Vf91),
    z2VUGE(z2VaYL),
    z2VR7t,
}
pub struct z2VaYL {
    pub field_0: signal_router::schema::lib::z2VbUg,
    pub field_1: signal_standard::schema::lib::z2VLyh,
}
pub enum z2VZMR {z2VPNU ( z2VbCv ,) , z2VRJ5 ( z2VUEJ ,) , z2VSbY ( z2VMyn ,) , z2VWPR ( z2VZs4 ,) , z2VXtU ( z2VShs ,) , z2VZzt ( z2VPBk ,) , z2VLEb ( z2VSuA ,) ,} 
pub enum z2VVKk {z2VLcZ ( z2VLSg ,) , z2VKx6 ( z2VWSR ,) , z2VYZY ( z2VZs4 ,) , z2VTdF ( z2VRn4 ,) , z2VQkd ( z2VXEz ,) ,} 
pub struct z2VWSR {
    pub field_0: z2VSet,
    pub field_1: z2VXGr,
}
