// @generated by schema-rust-next

#[rustfmt::skip]
pub type String = std::string::String;
#[rustfmt::skip]
pub type Integer = u64;
#[rustfmt::skip]
pub type Boolean = bool;
#[rustfmt::skip]
pub type Path = std::string::String;

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
pub use nota_next::{NotaDecodeError, NotaEncode, NotaSource};

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Grant(ChannelGrant);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Extend(ChannelExtension);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Revoke(ChannelRevocation);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Deny(AdjudicationDenial);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ChannelGranted(GrantedChannel);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ChannelExtended(ExtendedChannel);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ChannelRevoked(RevokedChannel);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AdjudicationDenied(DeniedAdjudication);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ChannelOrderRejected(RejectedChannelOrder);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RequestUnimplemented(UnimplementedRequest);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ChannelIdentifier(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AdjudicationRequestIdentifier(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TextBody(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TimestampNanoseconds(u64);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ComponentName {
    Mind,
    Message,
    Router,
    Terminal,
    Harness,
    System,
    Introspect,
    Orchestrate,
    Spirit,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct UnixUserIdentifier(u64);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SystemPrincipal(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EngineIdentifier(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct HostName(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct NetworkPeer(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct OtherPersonaEngine {
    pub engine_identifier: EngineIdentifier,
    pub host: HostName,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ConnectionClass {
    Owner,
    NonOwnerUser(UnixUserIdentifier),
    System(SystemPrincipal),
    OtherPersona(OtherPersonaEngine),
    Network(NetworkPeer),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ChannelEndpoint {
    Internal(ComponentName),
    External(ConnectionClass),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ChannelMessageKind {
    MessageIngressSubmission,
    MessageSubmission,
    InboxQuery,
    FocusObservation,
    PromptBufferObservation,
    MessageDelivery,
    TerminalInput,
    TerminalCapture,
    TerminalResize,
    TranscriptEvent,
    AdjudicationRequest,
    DeliveryNotification,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ChannelDuration {
    OneShot,
    Permanent,
    TimeBound(TimestampNanoseconds),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ChannelGrant {
    pub source: ChannelEndpoint,
    pub destination: ChannelEndpoint,
    pub kinds: Vec<ChannelMessageKind>,
    pub duration: ChannelDuration,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ChannelExtension {
    pub channel: ChannelIdentifier,
    pub duration: ChannelDuration,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ChannelRevocation {
    pub channel: ChannelIdentifier,
    pub reason: TextBody,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AdjudicationDenial {
    pub request: AdjudicationRequestIdentifier,
    pub reason: TextBody,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct GrantedChannel(ChannelIdentifier);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ExtendedChannel(ChannelIdentifier);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RevokedChannel(ChannelIdentifier);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DeniedAdjudication(AdjudicationRequestIdentifier);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum OperationKind {
    Grant,
    Extend,
    Revoke,
    Deny,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ChannelOrderRejectionReason {
    MetaAuthorityRequired,
    ChannelAlreadyExists,
    ChannelMissing,
    AdjudicationRequestMissing,
    PolicyRefused,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RejectedChannelOrder {
    pub operation: OperationKind,
    pub reason: ChannelOrderRejectionReason,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum UnimplementedReason {
    NotBuiltYet,
    DependencyNotReady,
    PolicyStoreUnavailable,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct UnimplementedRequest {
    pub operation: OperationKind,
    pub reason: UnimplementedReason,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    Grant(Grant),
    Extend(Extend),
    Revoke(Revoke),
    Deny(Deny),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    ChannelGranted(ChannelGranted),
    ChannelExtended(ChannelExtended),
    ChannelRevoked(ChannelRevoked),
    AdjudicationDenied(AdjudicationDenied),
    ChannelOrderRejected(ChannelOrderRejected),
    RequestUnimplemented(RequestUnimplemented),
}

#[rustfmt::skip]
impl Grant {
    pub fn new(payload: ChannelGrant) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ChannelGrant {
        &self.0
    }
    pub fn into_payload(self) -> ChannelGrant {
        self.0
    }
}
#[rustfmt::skip]
impl From<ChannelGrant> for Grant {
    fn from(payload: ChannelGrant) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Extend {
    pub fn new(payload: ChannelExtension) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ChannelExtension {
        &self.0
    }
    pub fn into_payload(self) -> ChannelExtension {
        self.0
    }
}
#[rustfmt::skip]
impl From<ChannelExtension> for Extend {
    fn from(payload: ChannelExtension) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Revoke {
    pub fn new(payload: ChannelRevocation) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ChannelRevocation {
        &self.0
    }
    pub fn into_payload(self) -> ChannelRevocation {
        self.0
    }
}
#[rustfmt::skip]
impl From<ChannelRevocation> for Revoke {
    fn from(payload: ChannelRevocation) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Deny {
    pub fn new(payload: AdjudicationDenial) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &AdjudicationDenial {
        &self.0
    }
    pub fn into_payload(self) -> AdjudicationDenial {
        self.0
    }
}
#[rustfmt::skip]
impl From<AdjudicationDenial> for Deny {
    fn from(payload: AdjudicationDenial) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ChannelGranted {
    pub fn new(payload: GrantedChannel) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &GrantedChannel {
        &self.0
    }
    pub fn into_payload(self) -> GrantedChannel {
        self.0
    }
}
#[rustfmt::skip]
impl From<GrantedChannel> for ChannelGranted {
    fn from(payload: GrantedChannel) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ChannelExtended {
    pub fn new(payload: ExtendedChannel) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ExtendedChannel {
        &self.0
    }
    pub fn into_payload(self) -> ExtendedChannel {
        self.0
    }
}
#[rustfmt::skip]
impl From<ExtendedChannel> for ChannelExtended {
    fn from(payload: ExtendedChannel) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ChannelRevoked {
    pub fn new(payload: RevokedChannel) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RevokedChannel {
        &self.0
    }
    pub fn into_payload(self) -> RevokedChannel {
        self.0
    }
}
#[rustfmt::skip]
impl From<RevokedChannel> for ChannelRevoked {
    fn from(payload: RevokedChannel) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl AdjudicationDenied {
    pub fn new(payload: DeniedAdjudication) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &DeniedAdjudication {
        &self.0
    }
    pub fn into_payload(self) -> DeniedAdjudication {
        self.0
    }
}
#[rustfmt::skip]
impl From<DeniedAdjudication> for AdjudicationDenied {
    fn from(payload: DeniedAdjudication) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ChannelOrderRejected {
    pub fn new(payload: RejectedChannelOrder) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RejectedChannelOrder {
        &self.0
    }
    pub fn into_payload(self) -> RejectedChannelOrder {
        self.0
    }
}
#[rustfmt::skip]
impl From<RejectedChannelOrder> for ChannelOrderRejected {
    fn from(payload: RejectedChannelOrder) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RequestUnimplemented {
    pub fn new(payload: UnimplementedRequest) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &UnimplementedRequest {
        &self.0
    }
    pub fn into_payload(self) -> UnimplementedRequest {
        self.0
    }
}
#[rustfmt::skip]
impl From<UnimplementedRequest> for RequestUnimplemented {
    fn from(payload: UnimplementedRequest) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ChannelIdentifier {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for ChannelIdentifier {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}
#[rustfmt::skip]
impl std::fmt::Display for ChannelIdentifier {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.payload().fmt(formatter)
    }
}
#[rustfmt::skip]
impl AsRef<str> for ChannelIdentifier {
    fn as_ref(&self) -> &str {
        self.payload().as_str()
    }
}
#[rustfmt::skip]
impl PartialEq<&str> for ChannelIdentifier {
    fn eq(&self, other: &&str) -> bool {
        self.payload() == other
    }
}

#[rustfmt::skip]
impl AdjudicationRequestIdentifier {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for AdjudicationRequestIdentifier {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}
#[rustfmt::skip]
impl std::fmt::Display for AdjudicationRequestIdentifier {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.payload().fmt(formatter)
    }
}
#[rustfmt::skip]
impl AsRef<str> for AdjudicationRequestIdentifier {
    fn as_ref(&self) -> &str {
        self.payload().as_str()
    }
}
#[rustfmt::skip]
impl PartialEq<&str> for AdjudicationRequestIdentifier {
    fn eq(&self, other: &&str) -> bool {
        self.payload() == other
    }
}

#[rustfmt::skip]
impl TextBody {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for TextBody {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}
#[rustfmt::skip]
impl std::fmt::Display for TextBody {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.payload().fmt(formatter)
    }
}
#[rustfmt::skip]
impl AsRef<str> for TextBody {
    fn as_ref(&self) -> &str {
        self.payload().as_str()
    }
}
#[rustfmt::skip]
impl PartialEq<&str> for TextBody {
    fn eq(&self, other: &&str) -> bool {
        self.payload() == other
    }
}

#[rustfmt::skip]
impl TimestampNanoseconds {
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
#[rustfmt::skip]
impl From<u64> for TimestampNanoseconds {
    fn from(payload: u64) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl UnixUserIdentifier {
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
#[rustfmt::skip]
impl From<u64> for UnixUserIdentifier {
    fn from(payload: u64) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SystemPrincipal {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for SystemPrincipal {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}
#[rustfmt::skip]
impl std::fmt::Display for SystemPrincipal {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.payload().fmt(formatter)
    }
}
#[rustfmt::skip]
impl AsRef<str> for SystemPrincipal {
    fn as_ref(&self) -> &str {
        self.payload().as_str()
    }
}
#[rustfmt::skip]
impl PartialEq<&str> for SystemPrincipal {
    fn eq(&self, other: &&str) -> bool {
        self.payload() == other
    }
}

#[rustfmt::skip]
impl EngineIdentifier {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for EngineIdentifier {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}
#[rustfmt::skip]
impl std::fmt::Display for EngineIdentifier {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.payload().fmt(formatter)
    }
}
#[rustfmt::skip]
impl AsRef<str> for EngineIdentifier {
    fn as_ref(&self) -> &str {
        self.payload().as_str()
    }
}
#[rustfmt::skip]
impl PartialEq<&str> for EngineIdentifier {
    fn eq(&self, other: &&str) -> bool {
        self.payload() == other
    }
}

#[rustfmt::skip]
impl HostName {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for HostName {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}
#[rustfmt::skip]
impl std::fmt::Display for HostName {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.payload().fmt(formatter)
    }
}
#[rustfmt::skip]
impl AsRef<str> for HostName {
    fn as_ref(&self) -> &str {
        self.payload().as_str()
    }
}
#[rustfmt::skip]
impl PartialEq<&str> for HostName {
    fn eq(&self, other: &&str) -> bool {
        self.payload() == other
    }
}

#[rustfmt::skip]
impl NetworkPeer {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for NetworkPeer {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}
#[rustfmt::skip]
impl std::fmt::Display for NetworkPeer {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.payload().fmt(formatter)
    }
}
#[rustfmt::skip]
impl AsRef<str> for NetworkPeer {
    fn as_ref(&self) -> &str {
        self.payload().as_str()
    }
}
#[rustfmt::skip]
impl PartialEq<&str> for NetworkPeer {
    fn eq(&self, other: &&str) -> bool {
        self.payload() == other
    }
}

#[rustfmt::skip]
impl GrantedChannel {
    pub fn new(payload: ChannelIdentifier) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ChannelIdentifier {
        &self.0
    }
    pub fn into_payload(self) -> ChannelIdentifier {
        self.0
    }
}
#[rustfmt::skip]
impl From<ChannelIdentifier> for GrantedChannel {
    fn from(payload: ChannelIdentifier) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ExtendedChannel {
    pub fn new(payload: ChannelIdentifier) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ChannelIdentifier {
        &self.0
    }
    pub fn into_payload(self) -> ChannelIdentifier {
        self.0
    }
}
#[rustfmt::skip]
impl From<ChannelIdentifier> for ExtendedChannel {
    fn from(payload: ChannelIdentifier) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RevokedChannel {
    pub fn new(payload: ChannelIdentifier) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ChannelIdentifier {
        &self.0
    }
    pub fn into_payload(self) -> ChannelIdentifier {
        self.0
    }
}
#[rustfmt::skip]
impl From<ChannelIdentifier> for RevokedChannel {
    fn from(payload: ChannelIdentifier) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl DeniedAdjudication {
    pub fn new(payload: AdjudicationRequestIdentifier) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &AdjudicationRequestIdentifier {
        &self.0
    }
    pub fn into_payload(self) -> AdjudicationRequestIdentifier {
        self.0
    }
}
#[rustfmt::skip]
impl From<AdjudicationRequestIdentifier> for DeniedAdjudication {
    fn from(payload: AdjudicationRequestIdentifier) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ConnectionClass {
    pub fn non_owner_user(payload: u64) -> Self {
        Self::NonOwnerUser(UnixUserIdentifier::new(payload))
    }
    pub fn system(payload: String) -> Self {
        Self::System(SystemPrincipal::new(payload))
    }
    pub fn other_persona(payload: OtherPersonaEngine) -> Self {
        Self::OtherPersona(payload)
    }
    pub fn network(payload: String) -> Self {
        Self::Network(NetworkPeer::new(payload))
    }
}

#[rustfmt::skip]
impl ChannelEndpoint {
    pub fn internal(payload: ComponentName) -> Self {
        Self::Internal(payload)
    }
    pub fn external(payload: ConnectionClass) -> Self {
        Self::External(payload)
    }
}

#[rustfmt::skip]
impl ChannelDuration {
    pub fn time_bound(payload: u64) -> Self {
        Self::TimeBound(TimestampNanoseconds::new(payload))
    }
}

#[rustfmt::skip]
impl Input {
    pub fn grant(payload: ChannelGrant) -> Self {
        Self::Grant(Grant::new(payload))
    }
    pub fn extend(payload: ChannelExtension) -> Self {
        Self::Extend(Extend::new(payload))
    }
    pub fn revoke(payload: ChannelRevocation) -> Self {
        Self::Revoke(Revoke::new(payload))
    }
    pub fn deny(payload: AdjudicationDenial) -> Self {
        Self::Deny(Deny::new(payload))
    }
}

#[rustfmt::skip]
impl Output {
    pub fn channel_granted(payload: GrantedChannel) -> Self {
        Self::ChannelGranted(ChannelGranted::new(payload))
    }
    pub fn channel_extended(payload: ExtendedChannel) -> Self {
        Self::ChannelExtended(ChannelExtended::new(payload))
    }
    pub fn channel_revoked(payload: RevokedChannel) -> Self {
        Self::ChannelRevoked(ChannelRevoked::new(payload))
    }
    pub fn adjudication_denied(payload: DeniedAdjudication) -> Self {
        Self::AdjudicationDenied(AdjudicationDenied::new(payload))
    }
    pub fn channel_order_rejected(payload: RejectedChannelOrder) -> Self {
        Self::ChannelOrderRejected(ChannelOrderRejected::new(payload))
    }
    pub fn request_unimplemented(payload: UnimplementedRequest) -> Self {
        Self::RequestUnimplemented(RequestUnimplemented::new(payload))
    }
}

#[rustfmt::skip]
impl From<UnixUserIdentifier> for ConnectionClass {
    fn from(payload: UnixUserIdentifier) -> Self {
        Self::NonOwnerUser(payload)
    }
}

#[rustfmt::skip]
impl From<SystemPrincipal> for ConnectionClass {
    fn from(payload: SystemPrincipal) -> Self {
        Self::System(payload)
    }
}

#[rustfmt::skip]
impl From<OtherPersonaEngine> for ConnectionClass {
    fn from(payload: OtherPersonaEngine) -> Self {
        Self::OtherPersona(payload)
    }
}

#[rustfmt::skip]
impl From<NetworkPeer> for ConnectionClass {
    fn from(payload: NetworkPeer) -> Self {
        Self::Network(payload)
    }
}

#[rustfmt::skip]
impl From<ComponentName> for ChannelEndpoint {
    fn from(payload: ComponentName) -> Self {
        Self::Internal(payload)
    }
}

#[rustfmt::skip]
impl From<ConnectionClass> for ChannelEndpoint {
    fn from(payload: ConnectionClass) -> Self {
        Self::External(payload)
    }
}

#[rustfmt::skip]
impl From<TimestampNanoseconds> for ChannelDuration {
    fn from(payload: TimestampNanoseconds) -> Self {
        Self::TimeBound(payload)
    }
}

#[rustfmt::skip]
impl From<Grant> for Input {
    fn from(payload: Grant) -> Self {
        Self::Grant(payload)
    }
}

#[rustfmt::skip]
impl From<Extend> for Input {
    fn from(payload: Extend) -> Self {
        Self::Extend(payload)
    }
}

#[rustfmt::skip]
impl From<Revoke> for Input {
    fn from(payload: Revoke) -> Self {
        Self::Revoke(payload)
    }
}

#[rustfmt::skip]
impl From<Deny> for Input {
    fn from(payload: Deny) -> Self {
        Self::Deny(payload)
    }
}

#[rustfmt::skip]
impl From<ChannelGranted> for Output {
    fn from(payload: ChannelGranted) -> Self {
        Self::ChannelGranted(payload)
    }
}

#[rustfmt::skip]
impl From<ChannelExtended> for Output {
    fn from(payload: ChannelExtended) -> Self {
        Self::ChannelExtended(payload)
    }
}

#[rustfmt::skip]
impl From<ChannelRevoked> for Output {
    fn from(payload: ChannelRevoked) -> Self {
        Self::ChannelRevoked(payload)
    }
}

#[rustfmt::skip]
impl From<AdjudicationDenied> for Output {
    fn from(payload: AdjudicationDenied) -> Self {
        Self::AdjudicationDenied(payload)
    }
}

#[rustfmt::skip]
impl From<ChannelOrderRejected> for Output {
    fn from(payload: ChannelOrderRejected) -> Self {
        Self::ChannelOrderRejected(payload)
    }
}

#[rustfmt::skip]
impl From<RequestUnimplemented> for Output {
    fn from(payload: RequestUnimplemented) -> Self {
        Self::RequestUnimplemented(payload)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
pub mod short_header {
    pub const INPUT_GRANT: u64 = 0x0000000000000000;
    pub const INPUT_EXTEND: u64 = 0x0001000000000000;
    pub const INPUT_REVOKE: u64 = 0x0002000000000000;
    pub const INPUT_DENY: u64 = 0x0003000000000000;
    pub const OUTPUT_CHANNEL_GRANTED: u64 = 0x0100000000000000;
    pub const OUTPUT_CHANNEL_EXTENDED: u64 = 0x0101000000000000;
    pub const OUTPUT_CHANNEL_REVOKED: u64 = 0x0102000000000000;
    pub const OUTPUT_ADJUDICATION_DENIED: u64 = 0x0103000000000000;
    pub const OUTPUT_CHANNEL_ORDER_REJECTED: u64 = 0x0104000000000000;
    pub const OUTPUT_REQUEST_UNIMPLEMENTED: u64 = 0x0105000000000000;
}

#[rustfmt::skip]
const SIGNAL_SHORT_HEADER_BYTE_COUNT: usize = 8;
#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SignalFrameError {
    ArchiveEncode,
    ArchiveDecode,
    FrameTooShort { found: usize },
    UnknownHeader { root_enum: &'static str, header: u64 },
    HeaderMismatch { expected: u64, found: u64 },
}
#[rustfmt::skip]
impl std::fmt::Display for SignalFrameError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ArchiveEncode => formatter.write_str("failed to encode rkyv archive"),
            Self::ArchiveDecode => formatter.write_str("failed to decode rkyv archive"),
            Self::FrameTooShort { found } => {
                write!(formatter, "signal frame too short: {found} bytes")
            }
            Self::UnknownHeader { root_enum, header } => {
                write!(formatter, "unknown {root_enum} short header 0x{header:016X}")
            }
            Self::HeaderMismatch { expected, found } => {
                write!(
                    formatter,
                    "decoded payload header mismatch: expected 0x{expected:016X}, found 0x{found:016X}"
                )
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for SignalFrameError {}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum InputRoute {
    Grant,
    Extend,
    Revoke,
    Deny,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum OutputRoute {
    ChannelGranted,
    ChannelExtended,
    ChannelRevoked,
    AdjudicationDenied,
    ChannelOrderRejected,
    RequestUnimplemented,
}

#[rustfmt::skip]
impl Input {
    pub fn route(&self) -> InputRoute {
        match self {
            Self::Grant(_) => InputRoute::Grant,
            Self::Extend(_) => InputRoute::Extend,
            Self::Revoke(_) => InputRoute::Revoke,
            Self::Deny(_) => InputRoute::Deny,
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::Grant(_) => short_header::INPUT_GRANT,
            Self::Extend(_) => short_header::INPUT_EXTEND,
            Self::Revoke(_) => short_header::INPUT_REVOKE,
            Self::Deny(_) => short_header::INPUT_DENY,
        }
    }
    pub fn route_from_short_header(header: u64) -> Result<InputRoute, SignalFrameError> {
        match header {
            short_header::INPUT_GRANT => Ok(InputRoute::Grant),
            short_header::INPUT_EXTEND => Ok(InputRoute::Extend),
            short_header::INPUT_REVOKE => Ok(InputRoute::Revoke),
            short_header::INPUT_DENY => Ok(InputRoute::Deny),
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Input",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(InputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}

#[rustfmt::skip]
impl Output {
    pub fn route(&self) -> OutputRoute {
        match self {
            Self::ChannelGranted(_) => OutputRoute::ChannelGranted,
            Self::ChannelExtended(_) => OutputRoute::ChannelExtended,
            Self::ChannelRevoked(_) => OutputRoute::ChannelRevoked,
            Self::AdjudicationDenied(_) => OutputRoute::AdjudicationDenied,
            Self::ChannelOrderRejected(_) => OutputRoute::ChannelOrderRejected,
            Self::RequestUnimplemented(_) => OutputRoute::RequestUnimplemented,
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::ChannelGranted(_) => short_header::OUTPUT_CHANNEL_GRANTED,
            Self::ChannelExtended(_) => short_header::OUTPUT_CHANNEL_EXTENDED,
            Self::ChannelRevoked(_) => short_header::OUTPUT_CHANNEL_REVOKED,
            Self::AdjudicationDenied(_) => short_header::OUTPUT_ADJUDICATION_DENIED,
            Self::ChannelOrderRejected(_) => short_header::OUTPUT_CHANNEL_ORDER_REJECTED,
            Self::RequestUnimplemented(_) => short_header::OUTPUT_REQUEST_UNIMPLEMENTED,
        }
    }
    pub fn route_from_short_header(
        header: u64,
    ) -> Result<OutputRoute, SignalFrameError> {
        match header {
            short_header::OUTPUT_CHANNEL_GRANTED => Ok(OutputRoute::ChannelGranted),
            short_header::OUTPUT_CHANNEL_EXTENDED => Ok(OutputRoute::ChannelExtended),
            short_header::OUTPUT_CHANNEL_REVOKED => Ok(OutputRoute::ChannelRevoked),
            short_header::OUTPUT_ADJUDICATION_DENIED => {
                Ok(OutputRoute::AdjudicationDenied)
            }
            short_header::OUTPUT_CHANNEL_ORDER_REJECTED => {
                Ok(OutputRoute::ChannelOrderRejected)
            }
            short_header::OUTPUT_REQUEST_UNIMPLEMENTED => {
                Ok(OutputRoute::RequestUnimplemented)
            }
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Output",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(OutputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}

#[rustfmt::skip]
impl signal_frame::RequestPayload for Input {}
#[rustfmt::skip]
impl signal_frame::SignalOperationHeads for Input {
    const HEADS: &'static [&'static str] = &["Grant", "Extend", "Revoke", "Deny"];
}
#[rustfmt::skip]
impl signal_frame::LogVariant for Input {
    fn log_variant(&self) -> u64 {
        self.short_header()
    }
}
#[rustfmt::skip]
pub type Frame = signal_frame::ExchangeFrame<Input, Output>;
#[rustfmt::skip]
pub type FrameBody = signal_frame::ExchangeFrameBody<Input, Output>;
#[rustfmt::skip]
pub type Request = signal_frame::Request<Input>;
#[rustfmt::skip]
pub type ReplyEnvelope = signal_frame::Reply<Output>;
#[rustfmt::skip]
pub type RequestBuilder = signal_frame::RequestBuilder<Input>;
#[rustfmt::skip]
impl Input {
    pub fn into_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let short_header = signal_frame::ShortHeader::new(self.short_header());
        let request = signal_frame::Request::from_payload(self);
        Frame::with_short_header(
            short_header,
            FrameBody::Request {
                exchange,
                request,
            },
        )
    }
}
#[rustfmt::skip]
impl Output {
    pub fn into_reply_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let short_header = signal_frame::ShortHeader::new(self.short_header());
        let reply = signal_frame::Reply::committed(
            signal_frame::NonEmpty::single(signal_frame::SubReply::Ok(self)),
        );
        Frame::with_short_header(
            short_header,
            FrameBody::Reply {
                exchange,
                reply,
            },
        )
    }
}
