// @generated by schema-rust-next

pub type String = std::string::String;
pub type Integer = u64;
pub type Boolean = bool;
pub type Path = std::string::String;

#[cfg(feature = "nota-text")]
pub use nota_next::{
    NotaDecode, NotaDecodeError, NotaEncode, NotaSource,
};

pub type Grant = ChannelGrant;

pub type Extend = ChannelExtension;

pub type Revoke = ChannelRevocation;

pub type Deny = AdjudicationDenial;

pub type ChannelGranted = GrantedChannel;

pub type ChannelExtended = ExtendedChannel;

pub type ChannelRevoked = RevokedChannel;

pub type AdjudicationDenied = DeniedAdjudication;

pub type ChannelOrderRejected = RejectedChannelOrder;

pub type RequestUnimplemented = UnimplementedRequest;

pub type ChannelIdentifier = String;

pub type AdjudicationRequestIdentifier = String;

pub type TextBody = String;

pub type TimestampNanoseconds = u64;

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ComponentName {
    Mind,
    Message,
    Router,
    Terminal,
    Harness,
    System,
    Introspect,
    Orchestrate,
    Spirit,
}

pub type UnixUserIdentifier = u64;

pub type SystemPrincipal = String;

pub type EngineIdentifier = String;

pub type HostName = String;

pub type NetworkPeer = String;

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct OtherPersonaEngine {
    pub engine_identifier: EngineIdentifier,
    pub host: HostName,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ConnectionClass {
    Owner,
    NonOwnerUser(UnixUserIdentifier),
    System(SystemPrincipal),
    OtherPersona(OtherPersonaEngine),
    Network(NetworkPeer),
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ChannelEndpoint {
    Internal(ComponentName),
    External(ConnectionClass),
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ChannelMessageKind {
    MessageIngressSubmission,
    MessageSubmission,
    InboxQuery,
    FocusObservation,
    PromptBufferObservation,
    MessageDelivery,
    TerminalInput,
    TerminalCapture,
    TerminalResize,
    TranscriptEvent,
    AdjudicationRequest,
    DeliveryNotification,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ChannelDuration {
    OneShot,
    Permanent,
    TimeBound(TimestampNanoseconds),
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ChannelGrant {
    pub source: ChannelEndpoint,
    pub destination: ChannelEndpoint,
    pub kinds: Vec<ChannelMessageKind>,
    pub duration: ChannelDuration,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ChannelExtension {
    pub channel: ChannelIdentifier,
    pub duration: ChannelDuration,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ChannelRevocation {
    pub channel: ChannelIdentifier,
    pub reason: TextBody,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AdjudicationDenial {
    pub request: AdjudicationRequestIdentifier,
    pub reason: TextBody,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct GrantedChannel(pub ChannelIdentifier);

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ExtendedChannel(pub ChannelIdentifier);

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RevokedChannel(pub ChannelIdentifier);

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DeniedAdjudication(pub AdjudicationRequestIdentifier);

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum OperationKind {
    Grant,
    Extend,
    Revoke,
    Deny,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ChannelOrderRejectionReason {
    MetaAuthorityRequired,
    ChannelAlreadyExists,
    ChannelMissing,
    AdjudicationRequestMissing,
    PolicyRefused,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RejectedChannelOrder {
    pub operation: OperationKind,
    pub reason: ChannelOrderRejectionReason,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum UnimplementedReason {
    NotBuiltYet,
    DependencyNotReady,
    PolicyStoreUnavailable,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct UnimplementedRequest {
    pub operation: OperationKind,
    pub reason: UnimplementedReason,
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    Grant(Grant),
    Extend(Extend),
    Revoke(Revoke),
    Deny(Deny),
}

#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    ChannelGranted(ChannelGranted),
    ChannelExtended(ChannelExtended),
    ChannelRevoked(ChannelRevoked),
    AdjudicationDenied(AdjudicationDenied),
    ChannelOrderRejected(ChannelOrderRejected),
    RequestUnimplemented(RequestUnimplemented),
}

impl GrantedChannel {
    pub fn new(payload: ChannelIdentifier) -> Self {
        Self(payload)
    }

    pub fn payload(&self) -> &ChannelIdentifier {
        &self.0
    }

    pub fn into_payload(self) -> ChannelIdentifier {
        self.0
    }
}

impl From<ChannelIdentifier> for GrantedChannel {
    fn from(payload: ChannelIdentifier) -> Self {
        Self::new(payload)
    }
}

impl ExtendedChannel {
    pub fn new(payload: ChannelIdentifier) -> Self {
        Self(payload)
    }

    pub fn payload(&self) -> &ChannelIdentifier {
        &self.0
    }

    pub fn into_payload(self) -> ChannelIdentifier {
        self.0
    }
}

impl From<ChannelIdentifier> for ExtendedChannel {
    fn from(payload: ChannelIdentifier) -> Self {
        Self::new(payload)
    }
}

impl RevokedChannel {
    pub fn new(payload: ChannelIdentifier) -> Self {
        Self(payload)
    }

    pub fn payload(&self) -> &ChannelIdentifier {
        &self.0
    }

    pub fn into_payload(self) -> ChannelIdentifier {
        self.0
    }
}

impl From<ChannelIdentifier> for RevokedChannel {
    fn from(payload: ChannelIdentifier) -> Self {
        Self::new(payload)
    }
}

impl DeniedAdjudication {
    pub fn new(payload: AdjudicationRequestIdentifier) -> Self {
        Self(payload)
    }

    pub fn payload(&self) -> &AdjudicationRequestIdentifier {
        &self.0
    }

    pub fn into_payload(self) -> AdjudicationRequestIdentifier {
        self.0
    }
}

impl From<AdjudicationRequestIdentifier> for DeniedAdjudication {
    fn from(payload: AdjudicationRequestIdentifier) -> Self {
        Self::new(payload)
    }
}

impl ConnectionClass {
    pub fn non_owner_user(payload: UnixUserIdentifier) -> Self {
        Self::NonOwnerUser(payload)
    }

    pub fn system(payload: SystemPrincipal) -> Self {
        Self::System(payload)
    }

    pub fn other_persona(payload: OtherPersonaEngine) -> Self {
        Self::OtherPersona(payload)
    }

    pub fn network(payload: NetworkPeer) -> Self {
        Self::Network(payload)
    }
}

impl ChannelEndpoint {
    pub fn internal(payload: ComponentName) -> Self {
        Self::Internal(payload)
    }

    pub fn external(payload: ConnectionClass) -> Self {
        Self::External(payload)
    }
}

impl ChannelDuration {
    pub fn time_bound(payload: TimestampNanoseconds) -> Self {
        Self::TimeBound(payload)
    }
}

impl Input {
    pub fn grant(payload: Grant) -> Self {
        Self::Grant(payload)
    }

    pub fn extend(payload: Extend) -> Self {
        Self::Extend(payload)
    }

    pub fn revoke(payload: Revoke) -> Self {
        Self::Revoke(payload)
    }

    pub fn deny(payload: Deny) -> Self {
        Self::Deny(payload)
    }
}

impl Output {
    pub fn channel_granted(payload: ChannelGranted) -> Self {
        Self::ChannelGranted(payload)
    }

    pub fn channel_extended(payload: ChannelExtended) -> Self {
        Self::ChannelExtended(payload)
    }

    pub fn channel_revoked(payload: ChannelRevoked) -> Self {
        Self::ChannelRevoked(payload)
    }

    pub fn adjudication_denied(payload: AdjudicationDenied) -> Self {
        Self::AdjudicationDenied(payload)
    }

    pub fn channel_order_rejected(payload: ChannelOrderRejected) -> Self {
        Self::ChannelOrderRejected(payload)
    }

    pub fn request_unimplemented(payload: RequestUnimplemented) -> Self {
        Self::RequestUnimplemented(payload)
    }
}

impl From<OtherPersonaEngine> for ConnectionClass {
    fn from(payload: OtherPersonaEngine) -> Self {
        Self::OtherPersona(payload)
    }
}

impl From<ComponentName> for ChannelEndpoint {
    fn from(payload: ComponentName) -> Self {
        Self::Internal(payload)
    }
}

impl From<ConnectionClass> for ChannelEndpoint {
    fn from(payload: ConnectionClass) -> Self {
        Self::External(payload)
    }
}

#[cfg(feature = "nota-text")]
impl ComponentName {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl OtherPersonaEngine {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl ConnectionClass {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl ChannelEndpoint {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl ChannelMessageKind {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl ChannelDuration {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl ChannelGrant {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl ChannelExtension {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl ChannelRevocation {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl AdjudicationDenial {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl GrantedChannel {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl ExtendedChannel {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl RevokedChannel {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl DeniedAdjudication {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl OperationKind {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl ChannelOrderRejectionReason {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl RejectedChannelOrder {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl UnimplementedReason {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl UnimplementedRequest {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl Input {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;

    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}

#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[cfg(feature = "nota-text")]
impl Output {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }

    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;

    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}

#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

pub mod short_header {
    pub const INPUT_GRANT: u64 = 0x0000000000000000;
    pub const INPUT_EXTEND: u64 = 0x0001000000000000;
    pub const INPUT_REVOKE: u64 = 0x0002000000000000;
    pub const INPUT_DENY: u64 = 0x0003000000000000;
    pub const OUTPUT_CHANNEL_GRANTED: u64 = 0x0100000000000000;
    pub const OUTPUT_CHANNEL_EXTENDED: u64 = 0x0101000000000000;
    pub const OUTPUT_CHANNEL_REVOKED: u64 = 0x0102000000000000;
    pub const OUTPUT_ADJUDICATION_DENIED: u64 = 0x0103000000000000;
    pub const OUTPUT_CHANNEL_ORDER_REJECTED: u64 = 0x0104000000000000;
    pub const OUTPUT_REQUEST_UNIMPLEMENTED: u64 = 0x0105000000000000;
}

